### ISSUE TITLE
Import external module

### ISSUE THREAD

**Issue by MGlolenstine** [saleae/logic2-examples#11]
Is there a way to include functionality from a wheel into the parser?
I've written a parser library in Rust, but I'd like to inspect it.
Using [`maturin`](https://github.com/PyO3/maturin), I've compiled it to `.whl` (and can be extracted to `__init__.py` and `<module name>.pyd`), but I'm unsure how to include it.

## I've tried:
- including it using `ctypes`
```python
import ctypes
packet_parser_python = ctypes.CDLL('packet_parser_python/packet_parser_python.cp311-win_amd64.pyd')
```
which tries to open the library from `C:\Program Files\Logic\packet_parser_python\packet_parser_python.cp311-win_amd64.pyd`, but after I've copied the files there, it still doesn't seem to load them correctly.

- installing the wheel using `py -m pip install <module-name>.whl`, but even if the `py` REPL interpreter finds it, Logic doesn't.

I'm new to binary packages in Python, and your extensions, so I'd like to know if that's possible.

**Comment by Marcus10110** [comment]
Good question. The short answer is we don't officially support loading external packages, native or otherwise yet. However for local development you might be able to get this to work by targeting the same version of python we ship with our software. We're able to load numpy, another native module, without trouble, so I expect that we should be able to load yours too. Our Software ships with python 3.8.2.

We package a python interpreter with our software, rather than use a locally installed python, to ensure that all marketplace extensions are always run with the same version of python.

Let us know if that's all it takes to fix this, or if you still have trouble with it.

**Comment by MGlolenstine** [comment]
One of the issues was that I was using wheels packaged for Python 3.11; once that was resolved, I had to extract the `.whl` and fix the paths to the module to fix recursive import (I think this is an issue with PyO3).

After the module was importable, I just had to put it next to the `HighLevelAnalyzer.py` and import it as usual, which made it work without an issue.

Thank you for your help!

### Note for the future reference.
- Build for Python 3.8.2
- Extract the wheel and place the `.pyd` file into a subdirectory and make it importable
- Import the dependency normally
